spring:
profiles:
    active: local
datasource:
  driver-class-name: org.postgresql.Driver
  platform: postgres
  url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
  username: postgres
  password: root
jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        hibernate.hbm2ddl.auto: none
    show-sql: true